tasks/api/urls.py
from django.urls import path
from . import views

app_name = 'tasks_api'

urlpatterns = [
    path('', views.index, name="index")
]

tasks/urls.py
from django.urls import path
from . import views

app_name = 'tasks'

urlpatterns = [
    path('', views.index, name="index"),
    path('newtask/', views.new_task, name="newtask"),
    path('setdone/<int:task_id>', views.task_change, name="change"),
    path('delete/<int:task_id>', views.task_delete, name="delete")
]

todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tasks.urls')),
    path('users/', include('users.urls')),
    path('api/tasks/', include('tasks.api.urls'))
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name="login"),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('register/', views.register, name="register"),
    path('profile/', views.profile, name="profile")
]

tasks/models.py
from django.db import models

from django.contrib.auth.models import User


class Task(models.Model):
    title = models.CharField(max_length=450)
    is_done = models.BooleanField(default=False)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

users/models.py
from django.db import models

# Create your models here.

tasks/api/views.py
from django.http import JsonResponse
from tasks.models import Task

# Will probably replace this with the DRF

def index(request):
    tasks = Task.objects.all().values()

    return JsonResponse({'tasks': 'nothing here xddd'})

tasks/views.py
from django.shortcuts import render, HttpResponse, HttpResponseRedirect, reverse
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from .decorators import is_author

from .models import Task

# Todo: Learn how to comment code.

@login_required
def index(request):
    """
    View that displays all the tasks belonging to a user.
    """
    tasks = Task.objects.filter(author=request.user).order_by('is_done')

    context = {
        'tasks': tasks
    }
    template = 'tasks/index.html'

    return render(request, template, context)


@login_required
def new_task(request):
    """
    View that creates a new task
    """
    t = request.POST['title']
    new_task = Task(title = t)
    new_task.author = request.user
    new_task.save()
    return HttpResponseRedirect(reverse('tasks:index'))


@login_required
@is_author
def task_change(request, task_id):
    """
    View that toggles a tasks is_done state
    """
    task = Task.objects.get(pk=task_id)
    # Toggle task state
    task.is_done = not task.is_done
    task.save()
    return HttpResponseRedirect(reverse('tasks:index'))


@login_required
@is_author
def task_delete(request, task_id):
    """
    View that deletes a task
    """
    task = Task.objects.get(pk=task_id)
    task.delete()

    messages.success(request, 'Task successfully deleted.')

    return HttpResponseRedirect(reverse('tasks:index'))

users/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login, authenticate
from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

# Todo: Subclass login view and add title

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            messages.success(request, 'Successfully registered')

            return redirect('tasks:index')
    else:
        form = UserCreationForm()

    context = {
        'form': form,
        'title': 'Register'
    }
    template = 'users/register.html'

    return render(request, template, context)


@login_required
def profile(request):
    user = request.user

    context = {
        'user': user,
        'title': 'Profile'
    }
    template = 'users/profile.html'

    return render(request, template, context)

tasks/templates/tasks/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  {% if title %}
    <title>{{ title }} | Todo-app</title>
  {% else %}
    <title>Todo-app</title>
  {% endif %}
  <link rel="stylesheet" href="{% static 'tasks/css/main.css' %}">
  {% block js %}{% endblock %}
</head>

<body>
  <nav class="navbar">

    <ul>
      <li><a href="{% url 'tasks:index' %}">Tasks</a></li>
      {% if user.is_authenticated %}
        <li><a href="{% url 'users:profile' %}">My account</a></li>
        <li><a href="{% url 'users:logout' %}">Log out</a></li>
      {% else %}
        <li><a href="{% url 'users:login' %}">Log in</a></li>
        <li><a href="{% url 'users:register' %}">Register</a></li>
      {% endif %}
    </ul>

  </nav>

  {% if messages %}
    {% for message in messages %}
      <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</div>
    {% endfor %}
  {% endif %}

  <main class="container content">
    {% block content %}{% endblock %}
  </main>

  <footer class="footer">

      <div class="footer-item">
        <p>&copy; 2019 <a href="https://github.com/wilsandbrink" target="_blank" rel="noopener noreferrer">wilsandbrink</a></p> 
      </div>
  
      <div class="footer-item-right">
        <nav class="social-links">
          <a href="https://github.com/wilsandbrink/horrible-todo" class="social-link" target="_blank" rel="noopener noreferrer">
            {% include 'tasks/partials/icons/github.html' %}
          </a>
        </nav>
      </div>
  
    </footer>
</body>
</html>

tasks/templates/tasks/index.html
{% extends 'tasks/base.html' %}
{% load static %}

{% block content %}
  <div class="logojk">
    <h1>Todo-app</h1>
    <form action="{% url 'tasks:newtask' %}" method="POST" class="taskform">
      {% csrf_token %}
      <input class="taskinput" type="text" name="title">
      <input class="tasksubmit" type="submit" value="Create">
    </form>
  </div>
  {% if tasks %}
  <table>
    <tr>
      <th>Title</th>
      <th>State</th>
      <th>Delete</th>
    </tr>
    {% for task in tasks %}
      {% include 'tasks/partials/task.html' %}
    {% endfor %}
  </table>
  {% else %}
  <p>No tasks.</p>
  {% endif %}
{% endblock %}

{% block js %}
  <script src="{% static 'tasks/js/taskchange.js' %}"></script>
{% endblock %}

tasks/templates/tasks/partials/icons/github.html
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>GitHub icon</title><path d="M12 .297c-6.63 0-12 5.373-12 12 0 5.303 3.438 9.8 8.205 11.385.6.113.82-.258.82-.577 0-.285-.01-1.04-.015-2.04-3.338.724-4.042-1.61-4.042-1.61C4.422 18.07 3.633 17.7 3.633 17.7c-1.087-.744.084-.729.084-.729 1.205.084 1.838 1.236 1.838 1.236 1.07 1.835 2.809 1.305 3.495.998.108-.776.417-1.305.76-1.605-2.665-.3-5.466-1.332-5.466-5.93 0-1.31.465-2.38 1.235-3.22-.135-.303-.54-1.523.105-3.176 0 0 1.005-.322 3.3 1.23.96-.267 1.98-.399 3-.405 1.02.006 2.04.138 3 .405 2.28-1.552 3.285-1.23 3.285-1.23.645 1.653.24 2.873.12 3.176.765.84 1.23 1.91 1.23 3.22 0 4.61-2.805 5.625-5.475 5.92.42.36.81 1.096.81 2.22 0 1.606-.015 2.896-.015 3.286 0 .315.21.69.825.57C20.565 22.092 24 17.592 24 12.297c0-6.627-5.373-12-12-12"/></svg>

tasks/templates/tasks/partials/task.html
<tr>
  <td>
      <p>{{ task.title }}</p>
  </td>
  <!--<div class="task">-->
    <td>
  <form action="{% url 'tasks:change' task.id %}" method="POST" id='{{ task.id }}'>
    {% csrf_token %}
      Done: <input type="checkbox" name="is_done" id="{{ task.id }}" value="{{ task.id }}" {% if task.is_done %} checked {% endif %} onchange="taskChange('{{ task.id }}')">
  </form>
</td>
<td>
  <a class="taskdel" href="{% url 'tasks:delete' task.id %}">Delete</a>
</td>
  <!--</div>-->
</tr>

users/templates/users/login.html
{% extends 'tasks/base.html' %}

{% block content %}
<h2>Log in</h2><hr>
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Login</button>
  <small>Need an account? <a href="{% url 'users:register' %}">Register</a></small>
</form>
{% endblock %}

users/templates/users/logout.html
{% extends 'tasks/base.html' %}
{% block content %}
<h2>You have been logged out!</h2><hr>
<table>
  <tr><small><a href="{% url 'users:login' %}">Log in again.</a></small></tr>
</table>
{% endblock %}

users/templates/users/profile.html
{% extends 'tasks/base.html' %}

{% block content %}

<h2>Hello, {{ user.username }}</h2>

{% endblock %}

users/templates/users/register.html
{% extends 'tasks/base.html' %}

{% block content %}
<h2>Register</h2><hr>
<form method="POST">
  <table>
  {% csrf_token %}
  {{ form.as_p }}
  </table>
  <button type="submit">Register</button>
  <small>Already have an account? <a href="{% url 'users:login' %}">Login</a></small>
</form>
{% endblock %}